name: bruno_resume_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  responsive_framework: ^0.2.0
  animations: ^2.0.7
  injectable: ^1.5.3
  get_it: ^7.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4


flutter:
  uses-material-design: true