name: bruno_resume_flutter
description: Bruno Gabriel resume using Flutter
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  get_it: ^7.6.7
  injectable: ^2.3.5
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  url_launcher: ^6.2.4
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/resume.json
   