name: Deploy Flutter Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        working-directory: bruno_resume_flutter

      - name: Build Web
        run: flutter build web --wasm --release 
        working-directory: bruno_resume_flutter

      - name: Deploy
        working-directory: bruno_resume_flutter
        run: |
          cd build/web
          git init
          git config --global user.email bruno.gsantos89@gmail.com
          git config --global user.name brunogabriel
          git status
          git remote add origin https://${{secrets.TOKEN}}@github.com/brunogabriel/brunogabriel.github.io
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f