name: Deploy Pull Request

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
        working-directory: bruno_resume_flutter

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage --reporter github